// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hmxhuemjueznudjigozo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhteGh1ZW1qdWV6bnVkamlnb3pvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjU1NTU2MTcsImV4cCI6MjA4MTEzMTYxN30.y9MOWk_AUKixwUsq8Ed6ZFoLa2SgMhVL8nP4b-BKuSo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});